### ISSUE TITLE
Adding `llvm` to the container

### ISSUE THREAD

**Issue by linsyking** [joint-online-judge/tiger#10]
`llvm-symbolizer` is useful when debugging.

## Background

Many courses will check memory problems by using `asan`, `lsan` and `ubsan`. However, on JOJ it cannot show the precise line number because it cannot find `llvm-symbolizer`.

Installing `llvm` package can solve the problem.

**Comment by BoYanZh** [comment]
Could you please give a example record to let us make sure the problem can be solved by installing the package?

**Comment by linsyking** [comment]
Sure. I wonder which image JOJ is currently using. tiger or jd4?

**Comment by linsyking** [comment]
I use the jd4 image to test.
With `llvm` package installed:
```
=================================================================
==1469==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1512 byte(s) in 9 object(s) allocated from:
    #0 0x513fc0 in operator new(unsigned long) (/root/test/pms/pms-asan+0x513fc0)
    #1 0x52c7d6 in main /root/test/pms/pms.cpp:14:28
    #2 0x7f658a2afc86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)

Indirect leak of 3802 byte(s) in 9 object(s) allocated from:
    #0 0x513fc0 in operator new(unsigned long) (/root/test/pms/pms-asan+0x513fc0)
    #1 0x7f658b384ac6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x124ac6)

SUMMARY: AddressSanitizer: 5314 byte(s) leaked in 18 allocation(s).
```
Without `llvm`:
```
==1486==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1512 byte(s) in 9 object(s) allocated from:
    #0 0x513fc0  (/root/test/pms/pms-asan+0x513fc0)
    #1 0x52c7d6  (/root/test/pms/pms-asan+0x52c7d6)
    #2 0x7f33e1a30c86  (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)

Indirect leak of 3802 byte(s) in 9 object(s) allocated from:
    #0 0x513fc0  (/root/test/pms/pms-asan+0x513fc0)
    #1 0x7f33e2b05ac6  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x124ac6)

SUMMARY: AddressSanitizer: 5314 byte(s) leaked in 18 allocation(s).
```

The reason is written in [here](https://clang.llvm.org/docs/AddressSanitizer.html#symbolizing-the-reports)
